"""
Application-wide constants
Extracts magic numbers and strings for better maintainability
"""

# Confidence thresholds
AUTO_FIX_CONFIDENCE_THRESHOLD = 85
HIGH_CONFIDENCE_THRESHOLD = 85
MEDIUM_CONFIDENCE_THRESHOLD = 60
LOW_CONFIDENCE_THRESHOLD = 40

# ML thresholds
ML_AUTO_REJECT_PROBABILITY = 0.2
ML_AUTO_REJECT_CONFIDENCE = 0.7
ML_AUTO_APPROVE_PROBABILITY = 0.85
ML_AUTO_APPROVE_CONFIDENCE = 0.8
MIN_TRAINING_SAMPLES = 20

# Trend score thresholds
DEFAULT_MIN_TREND_SCORE = 70
HIGH_TREND_SCORE = 85
MEDIUM_TREND_SCORE = 70
LOW_TREND_SCORE = 50

# Pagination
DEFAULT_PAGE_LIMIT = 50
MAX_PAGE_LIMIT = 100

# Validation window
FIX_VALIDATION_WINDOW_SECONDS = 120

# Rate limiting
RATE_LIMIT_PER_MINUTE = 60
RATE_LIMIT_SCAN_PER_HOUR = 10

# Database
DB_POOL_SIZE = 10
DB_MAX_OVERFLOW = 20
DB_POOL_TIMEOUT = 30
DB_POOL_RECYCLE = 3600

# API Timeouts
DEFAULT_API_TIMEOUT = 10
SCAN_API_TIMEOUT = 60
LONG_OPERATION_TIMEOUT = 300

# Rejection rate analysis
HIGH_REJECTION_RATE = 50
LOW_REJECTION_RATE = 20
MIN_SAMPLES_FOR_ANALYSIS = 5
REJECTION_THRESHOLD_HIGH = 70
REJECTION_THRESHOLD_MEDIUM = 60

# Product limits
MAX_PRODUCTS_PER_SCAN = 50
RECENT_PRODUCTS_LIMIT = 30

# Description lengths
MAX_DESCRIPTION_LENGTH_TIKTOK = 200
MAX_KEYWORDS = 10
MAX_SELLING_POINTS = 7

# Backup retention
MAX_BACKUPS = 10
BACKUP_RETENTION_DAYS = 30
